// <auto-generated />
using System;
using AccesoDatos.Modelos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(VehiculosContext))]
    [Migration("20220210033931_pruebaTec")]
    partial class pruebaTec
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccesoDatos.Modelos.ConteoVehiculosDB", b =>
                {
                    b.Property<int>("idConteo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<string>("categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("hora")
                        .HasColumnType("int");

                    b.Property<string>("sentido")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idConteo");

                    b.ToTable("Conteos");
                });

            modelBuilder.Entity("AccesoDatos.Modelos.RecaudoVehiculoDB", b =>
                {
                    b.Property<int>("idRecaudo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("hora")
                        .HasColumnType("int");

                    b.Property<string>("sentido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("valorTabulado")
                        .HasColumnType("int");

                    b.HasKey("idRecaudo");

                    b.ToTable("Recaudos");
                });
#pragma warning restore 612, 618
        }
    }
}
